"""Markdown document generator for human-readable meeting notes.

Renders meeting metadata into YAML frontmatter and formats timestamped transcript
segments deterministically, maintaining human readability without requiring MeetTrace.
"""

from __future__ import annotations

from collections.abc import Sequence

from meettrace.storage.models import MeetingMetadata, PersistedSegment
from meettrace.transcription.models import TranscriptSegment


def format_timestamp_ms(ms: int) -> str:
    """Format millisecond offset into standard bracketed timestamp [HH:MM:SS].

    Args:
        ms: Millisecond offset from recording start.

    Returns:
        Formatted string, e.g. '[00:00:12]'.
    """
    total_seconds = max(0, ms // 1000)
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    seconds = total_seconds % 60
    return f"[{hours:02d}:{minutes:02d}:{seconds:02d}]"


def format_duration_ms(ms: int) -> str:
    """Format duration in milliseconds to HH:MM:SS string.

    Args:
        ms: Duration in milliseconds.

    Returns:
        Formatted string, e.g. '00:24:17'.
    """
    total_seconds = max(0, ms // 1000)
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    seconds = total_seconds % 60
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


def render_meeting_markdown(
    metadata: MeetingMetadata,
    segments: Sequence[TranscriptSegment | PersistedSegment],
    summary_sections: dict[str, str] | None = None,
) -> str:
    """Render meeting metadata and transcript into a human-readable Markdown document.

    Follows the deterministic OpenSpec layout with YAML frontmatter, header,
    and timestamped transcript blocks. Prepared for optional downstream sections
    (e.g., Summary, Action Items) without altering the transcript body.

    Args:
        metadata: MeetingMetadata domain model.
        segments: Ordered sequence of transcript segments.
        summary_sections: Optional mapping of section titles to Markdown content (for Phase 8).

    Returns:
        A complete UTF-8 Markdown document string.
    """
    duration_str = format_duration_ms(metadata.duration_ms)

    # Format language list
    if metadata.detected_languages:
        langs_list = ", ".join(f"{lang}" for lang in metadata.detected_languages)
    elif metadata.dominant_language:
        langs_list = metadata.dominant_language
    else:
        langs_list = "unknown"

    platform = None
    url = None
    if isinstance(metadata.source, dict):
        platform = metadata.source.get("platform")
        url = metadata.source.get("url")
    elif isinstance(metadata.source, str) and metadata.source:
        platform = metadata.source

    # YAML Frontmatter
    lines = [
        "---",
        f"meeting_id: {metadata.meeting_id}",
        f"started_at: {metadata.started_at}",
        f"ended_at: {metadata.ended_at}",
        f"duration: {duration_str}",
        f"languages: [{langs_list}]",
    ]
    if platform:
        lines.append(f"platform: {platform}")
    if url:
        lines.append(f"url: {url}")
    lines.extend(
        [
            f"schema_version: {metadata.schema_version}",
            "---",
            "",
            f"# {metadata.title}",
            "",
        ]
    )

    # Optional Summary sections (placed before transcript if generated by Phase 8 Gemini)
    if summary_sections:
        for title, content in summary_sections.items():
            lines.append(f"## {title}")
            lines.append("")
            lines.append(content.strip())
            lines.append("")

    # Transcript section
    lines.append("## Transcript")
    lines.append("")

    if not segments:
        lines.append("_No speech detected._")
    else:
        for seg in segments:
            time_tag = format_timestamp_ms(seg.start_ms)
            clean_text = seg.text.strip()
            if clean_text:
                lines.append(f"{time_tag} {clean_text}")

    lines.append("")
    return "\n".join(lines)
